#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::AccountSubtype
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/account_subtype"

describe Plaid::AccountSubtype do
  describe "test an instance of AccountSubtype" do
    it "should create an instance of AccountSubtype" do
      # instance = Plaid::AccountSubtype.new
      # (instance).should be_a(Plaid::AccountSubtype)
    end
  end
end
