#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::AddressNullable
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/address_nullable"

describe Plaid::AddressNullable do
  describe "test an instance of AddressNullable" do
    it "should create an instance of AddressNullable" do
      # instance = Plaid::AddressNullable.new
      # (instance).should be_a(Plaid::AddressNullable)
    end
  end

  describe "test attribute 'data'" do
    it "should work" do
      # instance = Plaid::AddressNullable.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'primary'" do
    it "should work" do
      # instance = Plaid::AddressNullable.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
