#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::AddressDataNullableNoRequiredFields
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/address_data_nullable_no_required_fields"

describe Plaid::AddressDataNullableNoRequiredFields do
  describe "test an instance of AddressDataNullableNoRequiredFields" do
    it "should create an instance of AddressDataNullableNoRequiredFields" do
      # instance = Plaid::AddressDataNullableNoRequiredFields.new
      # (instance).should be_a(Plaid::AddressDataNullableNoRequiredFields)
    end
  end

  describe "test attribute 'city'" do
    it "should work" do
      # instance = Plaid::AddressDataNullableNoRequiredFields.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'region'" do
    it "should work" do
      # instance = Plaid::AddressDataNullableNoRequiredFields.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'street'" do
    it "should work" do
      # instance = Plaid::AddressDataNullableNoRequiredFields.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'postal_code'" do
    it "should work" do
      # instance = Plaid::AddressDataNullableNoRequiredFields.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'country'" do
    it "should work" do
      # instance = Plaid::AddressDataNullableNoRequiredFields.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
