#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::AssetHolderName
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/asset_holder_name"

describe Plaid::AssetHolderName do
  describe "test an instance of AssetHolderName" do
    it "should create an instance of AssetHolderName" do
      # instance = Plaid::AssetHolderName.new
      # (instance).should be_a(Plaid::AssetHolderName)
    end
  end

  describe "test attribute 'full_name'" do
    it "should work" do
      # instance = Plaid::AssetHolderName.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
