#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::AssetReportCreateResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/asset_report_create_response"

describe Plaid::AssetReportCreateResponse do
  describe "test an instance of AssetReportCreateResponse" do
    it "should create an instance of AssetReportCreateResponse" do
      # instance = Plaid::AssetReportCreateResponse.new
      # (instance).should be_a(Plaid::AssetReportCreateResponse)
    end
  end

  describe "test attribute 'asset_report_token'" do
    it "should work" do
      # instance = Plaid::AssetReportCreateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'asset_report_id'" do
    it "should work" do
      # instance = Plaid::AssetReportCreateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::AssetReportCreateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
