#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::BankTransferType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/bank_transfer_type"

describe Plaid::BankTransferType do
  describe "test an instance of BankTransferType" do
    it "should create an instance of BankTransferType" do
      # instance = Plaid::BankTransferType.new
      # (instance).should be_a(Plaid::BankTransferType)
    end
  end
end
