#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::BankTransferNetwork
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/bank_transfer_network"

describe Plaid::BankTransferNetwork do
  describe "test an instance of BankTransferNetwork" do
    it "should create an instance of BankTransferNetwork" do
      # instance = Plaid::BankTransferNetwork.new
      # (instance).should be_a(Plaid::BankTransferNetwork)
    end
  end
end
