#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::BankTransferBalance
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/bank_transfer_balance"

describe Plaid::BankTransferBalance do
  describe "test an instance of BankTransferBalance" do
    it "should create an instance of BankTransferBalance" do
      # instance = Plaid::BankTransferBalance.new
      # (instance).should be_a(Plaid::BankTransferBalance)
    end
  end

  describe "test attribute 'available'" do
    it "should work" do
      # instance = Plaid::BankTransferBalance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'transactable'" do
    it "should work" do
      # instance = Plaid::BankTransferBalance.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
