#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::BankIncomeRefreshUpdateWebhook
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/bank_income_refresh_update_webhook"

describe Plaid::BankIncomeRefreshUpdateWebhook do
  describe "test an instance of BankIncomeRefreshUpdateWebhook" do
    it "should create an instance of BankIncomeRefreshUpdateWebhook" do
      # instance = Plaid::BankIncomeRefreshUpdateWebhook.new
      # (instance).should be_a(Plaid::BankIncomeRefreshUpdateWebhook)
    end
  end

  describe "test attribute 'webhook_type'" do
    it "should work" do
      # instance = Plaid::BankIncomeRefreshUpdateWebhook.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'webhook_code'" do
    it "should work" do
      # instance = Plaid::BankIncomeRefreshUpdateWebhook.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'user_id'" do
    it "should work" do
      # instance = Plaid::BankIncomeRefreshUpdateWebhook.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'environment'" do
    it "should work" do
      # instance = Plaid::BankIncomeRefreshUpdateWebhook.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
