#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::BaseReportTransaction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/base_report_transaction"

describe Plaid::BaseReportTransaction do
  describe "test an instance of BaseReportTransaction" do
    it "should create an instance of BaseReportTransaction" do
      # instance = Plaid::BaseReportTransaction.new
      # (instance).should be_a(Plaid::BaseReportTransaction)
    end
  end

  describe "test attribute 'amount'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'iso_currency_code'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'unofficial_currency_code'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'original_description'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'credit_category'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'check_number'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_transacted'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'location'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'merchant_name'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'pending'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'account_owner'" do
    it "should work" do
      # instance = Plaid::BaseReportTransaction.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
