#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::BeaconReportSyndicationListResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/beacon_report_syndication_list_response"

describe Plaid::BeaconReportSyndicationListResponse do
  describe "test an instance of BeaconReportSyndicationListResponse" do
    it "should create an instance of BeaconReportSyndicationListResponse" do
      # instance = Plaid::BeaconReportSyndicationListResponse.new
      # (instance).should be_a(Plaid::BeaconReportSyndicationListResponse)
    end
  end

  describe "test attribute 'beacon_report_syndications'" do
    it "should work" do
      # instance = Plaid::BeaconReportSyndicationListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'next_cursor'" do
    it "should work" do
      # instance = Plaid::BeaconReportSyndicationListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::BeaconReportSyndicationListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
