#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::CreditFreddieMacReportingInformation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/credit_freddie_mac_reporting_information"

describe Plaid::CreditFreddieMacReportingInformation do
  describe "test an instance of CreditFreddieMacReportingInformation" do
    it "should create an instance of CreditFreddieMacReportingInformation" do
      # instance = Plaid::CreditFreddieMacReportingInformation.new
      # (instance).should be_a(Plaid::CreditFreddieMacReportingInformation)
    end
  end

  describe "test attribute 'report_date_time'" do
    it "should work" do
      # instance = Plaid::CreditFreddieMacReportingInformation.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'report_identifier_type'" do
    it "should work" do
      # instance = Plaid::CreditFreddieMacReportingInformation.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'reporting_information_parent_identifier'" do
    it "should work" do
      # instance = Plaid::CreditFreddieMacReportingInformation.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'reporting_information_identifier'" do
    it "should work" do
      # instance = Plaid::CreditFreddieMacReportingInformation.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
