#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::CreditEmploymentItem
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/credit_employment_item"

describe Plaid::CreditEmploymentItem do
  describe "test an instance of CreditEmploymentItem" do
    it "should create an instance of CreditEmploymentItem" do
      # instance = Plaid::CreditEmploymentItem.new
      # (instance).should be_a(Plaid::CreditEmploymentItem)
    end
  end

  describe "test attribute 'item_id'" do
    it "should work" do
      # instance = Plaid::CreditEmploymentItem.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'employments'" do
    it "should work" do
      # instance = Plaid::CreditEmploymentItem.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'employment_report_token'" do
    it "should work" do
      # instance = Plaid::CreditEmploymentItem.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
