#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::CreditBankIncome
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/credit_bank_income"

describe Plaid::CreditBankIncome do
  describe "test an instance of CreditBankIncome" do
    it "should create an instance of CreditBankIncome" do
      # instance = Plaid::CreditBankIncome.new
      # (instance).should be_a(Plaid::CreditBankIncome)
    end
  end

  describe "test attribute 'bank_income_id'" do
    it "should work" do
      # instance = Plaid::CreditBankIncome.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'generated_time'" do
    it "should work" do
      # instance = Plaid::CreditBankIncome.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'days_requested'" do
    it "should work" do
      # instance = Plaid::CreditBankIncome.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'items'" do
    it "should work" do
      # instance = Plaid::CreditBankIncome.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'bank_income_summary'" do
    it "should work" do
      # instance = Plaid::CreditBankIncome.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'warnings'" do
    it "should work" do
      # instance = Plaid::CreditBankIncome.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
