#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::CreditBankIncomeErrorType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/credit_bank_income_error_type"

describe Plaid::CreditBankIncomeErrorType do
  describe "test an instance of CreditBankIncomeErrorType" do
    it "should create an instance of CreditBankIncomeErrorType" do
      # instance = Plaid::CreditBankIncomeErrorType.new
      # (instance).should be_a(Plaid::CreditBankIncomeErrorType)
    end
  end
end
