#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::Credit1099Payer
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/credit1099_payer"

describe Plaid::Credit1099Payer do
  describe "test an instance of Credit1099Payer" do
    it "should create an instance of Credit1099Payer" do
      # instance = Plaid::Credit1099Payer.new
      # (instance).should be_a(Plaid::Credit1099Payer)
    end
  end

  describe "test attribute 'address'" do
    it "should work" do
      # instance = Plaid::Credit1099Payer.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'name'" do
    it "should work" do
      # instance = Plaid::Credit1099Payer.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'tin'" do
    it "should work" do
      # instance = Plaid::Credit1099Payer.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'telephone_number'" do
    it "should work" do
      # instance = Plaid::Credit1099Payer.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
