#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::CreditFreddieMacService
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/credit_freddie_mac_service"

describe Plaid::CreditFreddieMacService do
  describe "test an instance of CreditFreddieMacService" do
    it "should create an instance of CreditFreddieMacService" do
      # instance = Plaid::CreditFreddieMacService.new
      # (instance).should be_a(Plaid::CreditFreddieMacService)
    end
  end

  describe "test attribute 'verification_of_asset'" do
    it "should work" do
      # instance = Plaid::CreditFreddieMacService.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'statuses'" do
    it "should work" do
      # instance = Plaid::CreditFreddieMacService.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
