#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::CreditBankStatementUploadObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/credit_bank_statement_upload_object"

describe Plaid::CreditBankStatementUploadObject do
  describe "test an instance of CreditBankStatementUploadObject" do
    it "should create an instance of CreditBankStatementUploadObject" do
      # instance = Plaid::CreditBankStatementUploadObject.new
      # (instance).should be_a(Plaid::CreditBankStatementUploadObject)
    end
  end

  describe "test attribute 'transactions'" do
    it "should work" do
      # instance = Plaid::CreditBankStatementUploadObject.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'document_metadata'" do
    it "should work" do
      # instance = Plaid::CreditBankStatementUploadObject.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'document_id'" do
    it "should work" do
      # instance = Plaid::CreditBankStatementUploadObject.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'bank_accounts'" do
    it "should work" do
      # instance = Plaid::CreditBankStatementUploadObject.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
