#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::DetectedAccount
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/detected_account"

describe Plaid::DetectedAccount do
  describe "test an instance of DetectedAccount" do
    it "should create an instance of DetectedAccount" do
      # instance = Plaid::DetectedAccount.new
      # (instance).should be_a(Plaid::DetectedAccount)
    end
  end

  describe "test attribute 'account_type'" do
    it "should work" do
      # instance = Plaid::DetectedAccount.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'account_subtype'" do
    it "should work" do
      # instance = Plaid::DetectedAccount.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'transaction_count'" do
    it "should work" do
      # instance = Plaid::DetectedAccount.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'oldest_transaction_date'" do
    it "should work" do
      # instance = Plaid::DetectedAccount.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'newest_transaction_date'" do
    it "should work" do
      # instance = Plaid::DetectedAccount.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'newest_transaction_amount'" do
    it "should work" do
      # instance = Plaid::DetectedAccount.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'total_outflows'" do
    it "should work" do
      # instance = Plaid::DetectedAccount.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'total_inflows'" do
    it "should work" do
      # instance = Plaid::DetectedAccount.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
