#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::DistributionBreakdown
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/distribution_breakdown"

describe Plaid::DistributionBreakdown do
  describe "test an instance of DistributionBreakdown" do
    it "should create an instance of DistributionBreakdown" do
      # instance = Plaid::DistributionBreakdown.new
      # (instance).should be_a(Plaid::DistributionBreakdown)
    end
  end

  describe "test attribute 'account_name'" do
    it "should work" do
      # instance = Plaid::DistributionBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'bank_name'" do
    it "should work" do
      # instance = Plaid::DistributionBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'current_amount'" do
    it "should work" do
      # instance = Plaid::DistributionBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'iso_currency_code'" do
    it "should work" do
      # instance = Plaid::DistributionBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'mask'" do
    it "should work" do
      # instance = Plaid::DistributionBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute '_type'" do
    it "should work" do
      # instance = Plaid::DistributionBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'unofficial_currency_code'" do
    it "should work" do
      # instance = Plaid::DistributionBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'current_pay'" do
    it "should work" do
      # instance = Plaid::DistributionBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
