#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::DocumentNameMatchCode
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/document_name_match_code"

describe Plaid::DocumentNameMatchCode do
  describe "test an instance of DocumentNameMatchCode" do
    it "should create an instance of DocumentNameMatchCode" do
      # instance = Plaid::DocumentNameMatchCode.new
      # (instance).should be_a(Plaid::DocumentNameMatchCode)
    end
  end
end
