#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::EntityScreeningHitUrls
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/entity_screening_hit_urls"

describe Plaid::EntityScreeningHitUrls do
  describe "test an instance of EntityScreeningHitUrls" do
    it "should create an instance of EntityScreeningHitUrls" do
      # instance = Plaid::EntityScreeningHitUrls.new
      # (instance).should be_a(Plaid::EntityScreeningHitUrls)
    end
  end

  describe "test attribute 'url'" do
    it "should work" do
      # instance = Plaid::EntityScreeningHitUrls.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
