#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::EntityScreeningHitPhoneNumbers
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/entity_screening_hit_phone_numbers"

describe Plaid::EntityScreeningHitPhoneNumbers do
  describe "test an instance of EntityScreeningHitPhoneNumbers" do
    it "should create an instance of EntityScreeningHitPhoneNumbers" do
      # instance = Plaid::EntityScreeningHitPhoneNumbers.new
      # (instance).should be_a(Plaid::EntityScreeningHitPhoneNumbers)
    end
  end

  describe "test attribute '_type'" do
    it "should work" do
      # instance = Plaid::EntityScreeningHitPhoneNumbers.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'phone_number'" do
    it "should work" do
      # instance = Plaid::EntityScreeningHitPhoneNumbers.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
