#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ExpirationDate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/expiration_date"

describe Plaid::ExpirationDate do
  describe "test an instance of ExpirationDate" do
    it "should create an instance of ExpirationDate" do
      # instance = Plaid::ExpirationDate.new
      # (instance).should be_a(Plaid::ExpirationDate)
    end
  end
end
