#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ExternalPaymentScheduleBase
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/external_payment_schedule_base"

describe Plaid::ExternalPaymentScheduleBase do
  describe "test an instance of ExternalPaymentScheduleBase" do
    it "should create an instance of ExternalPaymentScheduleBase" do
      # instance = Plaid::ExternalPaymentScheduleBase.new
      # (instance).should be_a(Plaid::ExternalPaymentScheduleBase)
    end
  end

  describe "test attribute 'interval'" do
    it "should work" do
      # instance = Plaid::ExternalPaymentScheduleBase.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'interval_execution_day'" do
    it "should work" do
      # instance = Plaid::ExternalPaymentScheduleBase.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'start_date'" do
    it "should work" do
      # instance = Plaid::ExternalPaymentScheduleBase.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'end_date'" do
    it "should work" do
      # instance = Plaid::ExternalPaymentScheduleBase.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'adjusted_start_date'" do
    it "should work" do
      # instance = Plaid::ExternalPaymentScheduleBase.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
