#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::IncomeVerificationPrecheckConfidence
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/income_verification_precheck_confidence"

describe Plaid::IncomeVerificationPrecheckConfidence do
  describe "test an instance of IncomeVerificationPrecheckConfidence" do
    it "should create an instance of IncomeVerificationPrecheckConfidence" do
      # instance = Plaid::IncomeVerificationPrecheckConfidence.new
      # (instance).should be_a(Plaid::IncomeVerificationPrecheckConfidence)
    end
  end
end
