#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::IncomeVerificationPrecheckResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/income_verification_precheck_response"

describe Plaid::IncomeVerificationPrecheckResponse do
  describe "test an instance of IncomeVerificationPrecheckResponse" do
    it "should create an instance of IncomeVerificationPrecheckResponse" do
      # instance = Plaid::IncomeVerificationPrecheckResponse.new
      # (instance).should be_a(Plaid::IncomeVerificationPrecheckResponse)
    end
  end

  describe "test attribute 'precheck_id'" do
    it "should work" do
      # instance = Plaid::IncomeVerificationPrecheckResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::IncomeVerificationPrecheckResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'confidence'" do
    it "should work" do
      # instance = Plaid::IncomeVerificationPrecheckResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
