#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::InstitutionsGetRequestOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/institutions_get_request_options"

describe Plaid::InstitutionsGetRequestOptions do
  describe "test an instance of InstitutionsGetRequestOptions" do
    it "should create an instance of InstitutionsGetRequestOptions" do
      # instance = Plaid::InstitutionsGetRequestOptions.new
      # (instance).should be_a(Plaid::InstitutionsGetRequestOptions)
    end
  end

  describe "test attribute 'products'" do
    it "should work" do
      # instance = Plaid::InstitutionsGetRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'routing_numbers'" do
    it "should work" do
      # instance = Plaid::InstitutionsGetRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'oauth'" do
    it "should work" do
      # instance = Plaid::InstitutionsGetRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'include_optional_metadata'" do
    it "should work" do
      # instance = Plaid::InstitutionsGetRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'include_auth_metadata'" do
    it "should work" do
      # instance = Plaid::InstitutionsGetRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'include_payment_initiation_metadata'" do
    it "should work" do
      # instance = Plaid::InstitutionsGetRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
