#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::InvestmentsHoldingsGetRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/investments_holdings_get_request"

describe Plaid::InvestmentsHoldingsGetRequest do
  describe "test an instance of InvestmentsHoldingsGetRequest" do
    it "should create an instance of InvestmentsHoldingsGetRequest" do
      # instance = Plaid::InvestmentsHoldingsGetRequest.new
      # (instance).should be_a(Plaid::InvestmentsHoldingsGetRequest)
    end
  end

  describe "test attribute 'client_id'" do
    it "should work" do
      # instance = Plaid::InvestmentsHoldingsGetRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'secret'" do
    it "should work" do
      # instance = Plaid::InvestmentsHoldingsGetRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'access_token'" do
    it "should work" do
      # instance = Plaid::InvestmentsHoldingsGetRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'options'" do
    it "should work" do
      # instance = Plaid::InvestmentsHoldingsGetRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
