#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::InvestmentsAuthGetRequestOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/investments_auth_get_request_options"

describe Plaid::InvestmentsAuthGetRequestOptions do
  describe "test an instance of InvestmentsAuthGetRequestOptions" do
    it "should create an instance of InvestmentsAuthGetRequestOptions" do
      # instance = Plaid::InvestmentsAuthGetRequestOptions.new
      # (instance).should be_a(Plaid::InvestmentsAuthGetRequestOptions)
    end
  end

  describe "test attribute 'account_ids'" do
    it "should work" do
      # instance = Plaid::InvestmentsAuthGetRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
