#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ItemPublicTokenExchangeResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/item_public_token_exchange_response"

describe Plaid::ItemPublicTokenExchangeResponse do
  describe "test an instance of ItemPublicTokenExchangeResponse" do
    it "should create an instance of ItemPublicTokenExchangeResponse" do
      # instance = Plaid::ItemPublicTokenExchangeResponse.new
      # (instance).should be_a(Plaid::ItemPublicTokenExchangeResponse)
    end
  end

  describe "test attribute 'access_token'" do
    it "should work" do
      # instance = Plaid::ItemPublicTokenExchangeResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'item_id'" do
    it "should work" do
      # instance = Plaid::ItemPublicTokenExchangeResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::ItemPublicTokenExchangeResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
