#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ItemStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/item_status"

describe Plaid::ItemStatus do
  describe "test an instance of ItemStatus" do
    it "should create an instance of ItemStatus" do
      # instance = Plaid::ItemStatus.new
      # (instance).should be_a(Plaid::ItemStatus)
    end
  end

  describe "test attribute 'investments'" do
    it "should work" do
      # instance = Plaid::ItemStatus.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'transactions'" do
    it "should work" do
      # instance = Plaid::ItemStatus.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'last_webhook'" do
    it "should work" do
      # instance = Plaid::ItemStatus.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
