#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::KYCCheckDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/kyc_check_details"

describe Plaid::KYCCheckDetails do
  describe "test an instance of KYCCheckDetails" do
    it "should create an instance of KYCCheckDetails" do
      # instance = Plaid::KYCCheckDetails.new
      # (instance).should be_a(Plaid::KYCCheckDetails)
    end
  end

  describe "test attribute 'status'" do
    it "should work" do
      # instance = Plaid::KYCCheckDetails.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address'" do
    it "should work" do
      # instance = Plaid::KYCCheckDetails.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'name'" do
    it "should work" do
      # instance = Plaid::KYCCheckDetails.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_of_birth'" do
    it "should work" do
      # instance = Plaid::KYCCheckDetails.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'id_number'" do
    it "should work" do
      # instance = Plaid::KYCCheckDetails.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'phone_number'" do
    it "should work" do
      # instance = Plaid::KYCCheckDetails.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
