#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::LastDataAccessTimes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/last_data_access_times"

describe Plaid::LastDataAccessTimes do
  describe "test an instance of LastDataAccessTimes" do
    it "should create an instance of LastDataAccessTimes" do
      # instance = Plaid::LastDataAccessTimes.new
      # (instance).should be_a(Plaid::LastDataAccessTimes)
    end
  end

  describe "test attribute 'application_id'" do
    it "should work" do
      # instance = Plaid::LastDataAccessTimes.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'account_balance_info'" do
    it "should work" do
      # instance = Plaid::LastDataAccessTimes.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'account_routing_number'" do
    it "should work" do
      # instance = Plaid::LastDataAccessTimes.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'contact_details'" do
    it "should work" do
      # instance = Plaid::LastDataAccessTimes.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'transactions'" do
    it "should work" do
      # instance = Plaid::LastDataAccessTimes.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'credit_and_loans'" do
    it "should work" do
      # instance = Plaid::LastDataAccessTimes.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'investments'" do
    it "should work" do
      # instance = Plaid::LastDataAccessTimes.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'payroll_info'" do
    it "should work" do
      # instance = Plaid::LastDataAccessTimes.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'transaction_risk_info'" do
    it "should work" do
      # instance = Plaid::LastDataAccessTimes.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
