#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::LinkSessionSuccess
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/link_session_success"

describe Plaid::LinkSessionSuccess do
  describe "test an instance of LinkSessionSuccess" do
    it "should create an instance of LinkSessionSuccess" do
      # instance = Plaid::LinkSessionSuccess.new
      # (instance).should be_a(Plaid::LinkSessionSuccess)
    end
  end

  describe "test attribute 'public_token'" do
    it "should work" do
      # instance = Plaid::LinkSessionSuccess.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'metadata'" do
    it "should work" do
      # instance = Plaid::LinkSessionSuccess.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
