#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::LinkDeliveryOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/link_delivery_options"

describe Plaid::LinkDeliveryOptions do
  describe "test an instance of LinkDeliveryOptions" do
    it "should create an instance of LinkDeliveryOptions" do
      # instance = Plaid::LinkDeliveryOptions.new
      # (instance).should be_a(Plaid::LinkDeliveryOptions)
    end
  end

  describe "test attribute 'recipient'" do
    it "should work" do
      # instance = Plaid::LinkDeliveryOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
