#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::LinkTokenCreateRequestUserName
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/link_token_create_request_user_name"

describe Plaid::LinkTokenCreateRequestUserName do
  describe "test an instance of LinkTokenCreateRequestUserName" do
    it "should create an instance of LinkTokenCreateRequestUserName" do
      # instance = Plaid::LinkTokenCreateRequestUserName.new
      # (instance).should be_a(Plaid::LinkTokenCreateRequestUserName)
    end
  end

  describe "test attribute 'given_name'" do
    it "should work" do
      # instance = Plaid::LinkTokenCreateRequestUserName.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'family_name'" do
    it "should work" do
      # instance = Plaid::LinkTokenCreateRequestUserName.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
