#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::OtherFilter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/other_filter"

describe Plaid::OtherFilter do
  describe "test an instance of OtherFilter" do
    it "should create an instance of OtherFilter" do
      # instance = Plaid::OtherFilter.new
      # (instance).should be_a(Plaid::OtherFilter)
    end
  end

  describe "test attribute 'account_subtypes'" do
    it "should work" do
      # instance = Plaid::OtherFilter.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
