#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::PartnerEndCustomerSecrets
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/partner_end_customer_secrets"

describe Plaid::PartnerEndCustomerSecrets do
  describe "test an instance of PartnerEndCustomerSecrets" do
    it "should create an instance of PartnerEndCustomerSecrets" do
      # instance = Plaid::PartnerEndCustomerSecrets.new
      # (instance).should be_a(Plaid::PartnerEndCustomerSecrets)
    end
  end

  describe "test attribute 'sandbox'" do
    it "should work" do
      # instance = Plaid::PartnerEndCustomerSecrets.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'development'" do
    it "should work" do
      # instance = Plaid::PartnerEndCustomerSecrets.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
