#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::PartnerEndCustomerTechnicalContact
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/partner_end_customer_technical_contact"

describe Plaid::PartnerEndCustomerTechnicalContact do
  describe "test an instance of PartnerEndCustomerTechnicalContact" do
    it "should create an instance of PartnerEndCustomerTechnicalContact" do
      # instance = Plaid::PartnerEndCustomerTechnicalContact.new
      # (instance).should be_a(Plaid::PartnerEndCustomerTechnicalContact)
    end
  end

  describe "test attribute 'given_name'" do
    it "should work" do
      # instance = Plaid::PartnerEndCustomerTechnicalContact.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'family_name'" do
    it "should work" do
      # instance = Plaid::PartnerEndCustomerTechnicalContact.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'email'" do
    it "should work" do
      # instance = Plaid::PartnerEndCustomerTechnicalContact.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
