#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::PaymentInitiationPayment
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/payment_initiation_payment"

describe Plaid::PaymentInitiationPayment do
  describe "test an instance of PaymentInitiationPayment" do
    it "should create an instance of PaymentInitiationPayment" do
      # instance = Plaid::PaymentInitiationPayment.new
      # (instance).should be_a(Plaid::PaymentInitiationPayment)
    end
  end

  describe "test attribute 'payment_id'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'amount'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'status'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'recipient_id'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'reference'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'adjusted_reference'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'last_status_update'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'schedule'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'refund_details'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'bacs'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'iban'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'refund_ids'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'amount_refunded'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'wallet_id'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'scheme'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'adjusted_scheme'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'consent_id'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'transaction_id'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationPayment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
