#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::PaymentProfileCreateResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/payment_profile_create_response"

describe Plaid::PaymentProfileCreateResponse do
  describe "test an instance of PaymentProfileCreateResponse" do
    it "should create an instance of PaymentProfileCreateResponse" do
      # instance = Plaid::PaymentProfileCreateResponse.new
      # (instance).should be_a(Plaid::PaymentProfileCreateResponse)
    end
  end

  describe "test attribute 'payment_profile_token'" do
    it "should work" do
      # instance = Plaid::PaymentProfileCreateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::PaymentProfileCreateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
