#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::PaymentInitiationRecipientGetResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/payment_initiation_recipient_get_response"

describe Plaid::PaymentInitiationRecipientGetResponse do
  describe "test an instance of PaymentInitiationRecipientGetResponse" do
    it "should create an instance of PaymentInitiationRecipientGetResponse" do
      # instance = Plaid::PaymentInitiationRecipientGetResponse.new
      # (instance).should be_a(Plaid::PaymentInitiationRecipientGetResponse)
    end
  end

  describe "test attribute 'recipient_id'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationRecipientGetResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'name'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationRecipientGetResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationRecipientGetResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'iban'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationRecipientGetResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'bacs'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationRecipientGetResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::PaymentInitiationRecipientGetResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
