#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::PaymentInitiationPaymentCreateStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/payment_initiation_payment_create_status"

describe Plaid::PaymentInitiationPaymentCreateStatus do
  describe "test an instance of PaymentInitiationPaymentCreateStatus" do
    it "should create an instance of PaymentInitiationPaymentCreateStatus" do
      # instance = Plaid::PaymentInitiationPaymentCreateStatus.new
      # (instance).should be_a(Plaid::PaymentInitiationPaymentCreateStatus)
    end
  end
end
