#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ProcessorBalanceGetRequestOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/processor_balance_get_request_options"

describe Plaid::ProcessorBalanceGetRequestOptions do
  describe "test an instance of ProcessorBalanceGetRequestOptions" do
    it "should create an instance of ProcessorBalanceGetRequestOptions" do
      # instance = Plaid::ProcessorBalanceGetRequestOptions.new
      # (instance).should be_a(Plaid::ProcessorBalanceGetRequestOptions)
    end
  end

  describe "test attribute 'min_last_updated_datetime'" do
    it "should work" do
      # instance = Plaid::ProcessorBalanceGetRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
