#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ProcessorTransactionsSyncRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/processor_transactions_sync_request"

describe Plaid::ProcessorTransactionsSyncRequest do
  describe "test an instance of ProcessorTransactionsSyncRequest" do
    it "should create an instance of ProcessorTransactionsSyncRequest" do
      # instance = Plaid::ProcessorTransactionsSyncRequest.new
      # (instance).should be_a(Plaid::ProcessorTransactionsSyncRequest)
    end
  end

  describe "test attribute 'client_id'" do
    it "should work" do
      # instance = Plaid::ProcessorTransactionsSyncRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'processor_token'" do
    it "should work" do
      # instance = Plaid::ProcessorTransactionsSyncRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'secret'" do
    it "should work" do
      # instance = Plaid::ProcessorTransactionsSyncRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'cursor'" do
    it "should work" do
      # instance = Plaid::ProcessorTransactionsSyncRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'count'" do
    it "should work" do
      # instance = Plaid::ProcessorTransactionsSyncRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'options'" do
    it "should work" do
      # instance = Plaid::ProcessorTransactionsSyncRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
