#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ProcessorTokenPermissionsSetRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/processor_token_permissions_set_request"

describe Plaid::ProcessorTokenPermissionsSetRequest do
  describe "test an instance of ProcessorTokenPermissionsSetRequest" do
    it "should create an instance of ProcessorTokenPermissionsSetRequest" do
      # instance = Plaid::ProcessorTokenPermissionsSetRequest.new
      # (instance).should be_a(Plaid::ProcessorTokenPermissionsSetRequest)
    end
  end

  describe "test attribute 'client_id'" do
    it "should work" do
      # instance = Plaid::ProcessorTokenPermissionsSetRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'secret'" do
    it "should work" do
      # instance = Plaid::ProcessorTokenPermissionsSetRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'processor_token'" do
    it "should work" do
      # instance = Plaid::ProcessorTokenPermissionsSetRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'products'" do
    it "should work" do
      # instance = Plaid::ProcessorTokenPermissionsSetRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
