#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ProcessorNumber
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/processor_number"

describe Plaid::ProcessorNumber do
  describe "test an instance of ProcessorNumber" do
    it "should create an instance of ProcessorNumber" do
      # instance = Plaid::ProcessorNumber.new
      # (instance).should be_a(Plaid::ProcessorNumber)
    end
  end

  describe "test attribute 'ach'" do
    it "should work" do
      # instance = Plaid::ProcessorNumber.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'eft'" do
    it "should work" do
      # instance = Plaid::ProcessorNumber.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'international'" do
    it "should work" do
      # instance = Plaid::ProcessorNumber.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'bacs'" do
    it "should work" do
      # instance = Plaid::ProcessorNumber.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
