#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ProxyType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/proxy_type"

describe Plaid::ProxyType do
  describe "test an instance of ProxyType" do
    it "should create an instance of ProxyType" do
      # instance = Plaid::ProxyType.new
      # (instance).should be_a(Plaid::ProxyType)
    end
  end
end
