#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::RecipientBACS
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/recipient_bacs"

describe Plaid::RecipientBACS do
  describe "test an instance of RecipientBACS" do
    it "should create an instance of RecipientBACS" do
      # instance = Plaid::RecipientBACS.new
      # (instance).should be_a(Plaid::RecipientBACS)
    end
  end

  describe "test attribute 'account'" do
    it "should work" do
      # instance = Plaid::RecipientBACS.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'sort_code'" do
    it "should work" do
      # instance = Plaid::RecipientBACS.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
