#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::RiskCheckBehavior
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/risk_check_behavior"

describe Plaid::RiskCheckBehavior do
  describe "test an instance of RiskCheckBehavior" do
    it "should create an instance of RiskCheckBehavior" do
      # instance = Plaid::RiskCheckBehavior.new
      # (instance).should be_a(Plaid::RiskCheckBehavior)
    end
  end

  describe "test attribute 'user_interactions'" do
    it "should work" do
      # instance = Plaid::RiskCheckBehavior.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'fraud_ring_detected'" do
    it "should work" do
      # instance = Plaid::RiskCheckBehavior.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'bot_detected'" do
    it "should work" do
      # instance = Plaid::RiskCheckBehavior.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
