#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::RiskCheckBehaviorFraudRingDetectedLabel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/risk_check_behavior_fraud_ring_detected_label"

describe Plaid::RiskCheckBehaviorFraudRingDetectedLabel do
  describe "test an instance of RiskCheckBehaviorFraudRingDetectedLabel" do
    it "should create an instance of RiskCheckBehaviorFraudRingDetectedLabel" do
      # instance = Plaid::RiskCheckBehaviorFraudRingDetectedLabel.new
      # (instance).should be_a(Plaid::RiskCheckBehaviorFraudRingDetectedLabel)
    end
  end
end
