#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::SandboxTransferTestClockAdvanceResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/sandbox_transfer_test_clock_advance_response"

describe Plaid::SandboxTransferTestClockAdvanceResponse do
  describe "test an instance of SandboxTransferTestClockAdvanceResponse" do
    it "should create an instance of SandboxTransferTestClockAdvanceResponse" do
      # instance = Plaid::SandboxTransferTestClockAdvanceResponse.new
      # (instance).should be_a(Plaid::SandboxTransferTestClockAdvanceResponse)
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::SandboxTransferTestClockAdvanceResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
