#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::SandboxPublicTokenCreateRequestOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/sandbox_public_token_create_request_options"

describe Plaid::SandboxPublicTokenCreateRequestOptions do
  describe "test an instance of SandboxPublicTokenCreateRequestOptions" do
    it "should create an instance of SandboxPublicTokenCreateRequestOptions" do
      # instance = Plaid::SandboxPublicTokenCreateRequestOptions.new
      # (instance).should be_a(Plaid::SandboxPublicTokenCreateRequestOptions)
    end
  end

  describe "test attribute 'webhook'" do
    it "should work" do
      # instance = Plaid::SandboxPublicTokenCreateRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'override_username'" do
    it "should work" do
      # instance = Plaid::SandboxPublicTokenCreateRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'override_password'" do
    it "should work" do
      # instance = Plaid::SandboxPublicTokenCreateRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'transactions'" do
    it "should work" do
      # instance = Plaid::SandboxPublicTokenCreateRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'income_verification'" do
    it "should work" do
      # instance = Plaid::SandboxPublicTokenCreateRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
