#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ServiceProductFulfillment
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/service_product_fulfillment"

describe Plaid::ServiceProductFulfillment do
  describe "test an instance of ServiceProductFulfillment" do
    it "should create an instance of ServiceProductFulfillment" do
      # instance = Plaid::ServiceProductFulfillment.new
      # (instance).should be_a(Plaid::ServiceProductFulfillment)
    end
  end

  describe "test attribute 'service_product_fulfillment_detail'" do
    it "should work" do
      # instance = Plaid::ServiceProductFulfillment.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
