#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::SignalEvaluateResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/signal_evaluate_response"

describe Plaid::SignalEvaluateResponse do
  describe "test an instance of SignalEvaluateResponse" do
    it "should create an instance of SignalEvaluateResponse" do
      # instance = Plaid::SignalEvaluateResponse.new
      # (instance).should be_a(Plaid::SignalEvaluateResponse)
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::SignalEvaluateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'scores'" do
    it "should work" do
      # instance = Plaid::SignalEvaluateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'core_attributes'" do
    it "should work" do
      # instance = Plaid::SignalEvaluateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'warnings'" do
    it "should work" do
      # instance = Plaid::SignalEvaluateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
