#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::SignalPaymentMethod
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/signal_payment_method"

describe Plaid::SignalPaymentMethod do
  describe "test an instance of SignalPaymentMethod" do
    it "should create an instance of SignalPaymentMethod" do
      # instance = Plaid::SignalPaymentMethod.new
      # (instance).should be_a(Plaid::SignalPaymentMethod)
    end
  end
end
