#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::SignalDevice
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/signal_device"

describe Plaid::SignalDevice do
  describe "test an instance of SignalDevice" do
    it "should create an instance of SignalDevice" do
      # instance = Plaid::SignalDevice.new
      # (instance).should be_a(Plaid::SignalDevice)
    end
  end

  describe "test attribute 'ip_address'" do
    it "should work" do
      # instance = Plaid::SignalDevice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'user_agent'" do
    it "should work" do
      # instance = Plaid::SignalDevice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
