#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::Source
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/source"

describe Plaid::Source do
  describe "test an instance of Source" do
    it "should create an instance of Source" do
      # instance = Plaid::Source.new
      # (instance).should be_a(Plaid::Source)
    end
  end
end
