#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::Strategy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/strategy"

describe Plaid::Strategy do
  describe "test an instance of Strategy" do
    it "should create an instance of Strategy" do
      # instance = Plaid::Strategy.new
      # (instance).should be_a(Plaid::Strategy)
    end
  end
end
