#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TaxpayerIdentifier
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/taxpayer_identifier"

describe Plaid::TaxpayerIdentifier do
  describe "test an instance of TaxpayerIdentifier" do
    it "should create an instance of TaxpayerIdentifier" do
      # instance = Plaid::TaxpayerIdentifier.new
      # (instance).should be_a(Plaid::TaxpayerIdentifier)
    end
  end

  describe "test attribute 'taxpayer_identifier_type'" do
    it "should work" do
      # instance = Plaid::TaxpayerIdentifier.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'taxpayer_identifier_value'" do
    it "should work" do
      # instance = Plaid::TaxpayerIdentifier.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
