#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TaxpayerIdentifiers
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/taxpayer_identifiers"

describe Plaid::TaxpayerIdentifiers do
  describe "test an instance of TaxpayerIdentifiers" do
    it "should create an instance of TaxpayerIdentifiers" do
      # instance = Plaid::TaxpayerIdentifiers.new
      # (instance).should be_a(Plaid::TaxpayerIdentifiers)
    end
  end

  describe "test attribute 'taxpayer_identifier'" do
    it "should work" do
      # instance = Plaid::TaxpayerIdentifiers.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
