#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TransferOriginatorFundingAccountUpdateResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/transfer_originator_funding_account_update_response"

describe Plaid::TransferOriginatorFundingAccountUpdateResponse do
  describe "test an instance of TransferOriginatorFundingAccountUpdateResponse" do
    it "should create an instance of TransferOriginatorFundingAccountUpdateResponse" do
      # instance = Plaid::TransferOriginatorFundingAccountUpdateResponse.new
      # (instance).should be_a(Plaid::TransferOriginatorFundingAccountUpdateResponse)
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::TransferOriginatorFundingAccountUpdateResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
