#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TransferQuestionnaireCreateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/transfer_questionnaire_create_request"

describe Plaid::TransferQuestionnaireCreateRequest do
  describe "test an instance of TransferQuestionnaireCreateRequest" do
    it "should create an instance of TransferQuestionnaireCreateRequest" do
      # instance = Plaid::TransferQuestionnaireCreateRequest.new
      # (instance).should be_a(Plaid::TransferQuestionnaireCreateRequest)
    end
  end

  describe "test attribute 'client_id'" do
    it "should work" do
      # instance = Plaid::TransferQuestionnaireCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'secret'" do
    it "should work" do
      # instance = Plaid::TransferQuestionnaireCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'originator_client_id'" do
    it "should work" do
      # instance = Plaid::TransferQuestionnaireCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'redirect_uri'" do
    it "should work" do
      # instance = Plaid::TransferQuestionnaireCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
