#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TransferSweepListRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/transfer_sweep_list_request"

describe Plaid::TransferSweepListRequest do
  describe "test an instance of TransferSweepListRequest" do
    it "should create an instance of TransferSweepListRequest" do
      # instance = Plaid::TransferSweepListRequest.new
      # (instance).should be_a(Plaid::TransferSweepListRequest)
    end
  end

  describe "test attribute 'client_id'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'secret'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'start_date'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'end_date'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'count'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'offset'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'amount'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'status'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'originator_client_id'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'funding_account_id'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'transfer_id'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'trigger'" do
    it "should work" do
      # instance = Plaid::TransferSweepListRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
