#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TransferEventSyncResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/transfer_event_sync_response"

describe Plaid::TransferEventSyncResponse do
  describe "test an instance of TransferEventSyncResponse" do
    it "should create an instance of TransferEventSyncResponse" do
      # instance = Plaid::TransferEventSyncResponse.new
      # (instance).should be_a(Plaid::TransferEventSyncResponse)
    end
  end

  describe "test attribute 'transfer_events'" do
    it "should work" do
      # instance = Plaid::TransferEventSyncResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::TransferEventSyncResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
