#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TransferCreateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/transfer_create_request"

describe Plaid::TransferCreateRequest do
  describe "test an instance of TransferCreateRequest" do
    it "should create an instance of TransferCreateRequest" do
      # instance = Plaid::TransferCreateRequest.new
      # (instance).should be_a(Plaid::TransferCreateRequest)
    end
  end

  describe "test attribute 'client_id'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'secret'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'idempotency_key'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'access_token'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'account_id'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'authorization_id'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute '_type'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'network'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'amount'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'description'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'ach_class'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'user'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'metadata'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'origination_account_id'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'iso_currency_code'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'test_clock_id'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'facilitator_fee'" do
    it "should work" do
      # instance = Plaid::TransferCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
