#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TransferAuthorizationCreateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/transfer_authorization_create_request"

describe Plaid::TransferAuthorizationCreateRequest do
  describe "test an instance of TransferAuthorizationCreateRequest" do
    it "should create an instance of TransferAuthorizationCreateRequest" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # (instance).should be_a(Plaid::TransferAuthorizationCreateRequest)
    end
  end

  describe "test attribute 'client_id'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'secret'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'access_token'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'account_id'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'funding_account_id'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'payment_profile_token'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute '_type'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'network'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'amount'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'ach_class'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'user'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'device'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'origination_account_id'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'iso_currency_code'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'idempotency_key'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'user_present'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'with_guarantee'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'beacon_session_id'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'originator_client_id'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'credit_funds_source'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'test_clock_id'" do
    it "should work" do
      # instance = Plaid::TransferAuthorizationCreateRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
