#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TransactionsRecurringMergeInput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/transactions_recurring_merge_input"

describe Plaid::TransactionsRecurringMergeInput do
  describe "test an instance of TransactionsRecurringMergeInput" do
    it "should create an instance of TransactionsRecurringMergeInput" do
      # instance = Plaid::TransactionsRecurringMergeInput.new
      # (instance).should be_a(Plaid::TransactionsRecurringMergeInput)
    end
  end

  describe "test attribute 'stream_ids'" do
    it "should work" do
      # instance = Plaid::TransactionsRecurringMergeInput.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
