#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TransferIntentGetFailureReason
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/transfer_intent_get_failure_reason"

describe Plaid::TransferIntentGetFailureReason do
  describe "test an instance of TransferIntentGetFailureReason" do
    it "should create an instance of TransferIntentGetFailureReason" do
      # instance = Plaid::TransferIntentGetFailureReason.new
      # (instance).should be_a(Plaid::TransferIntentGetFailureReason)
    end
  end

  describe "test attribute 'error_type'" do
    it "should work" do
      # instance = Plaid::TransferIntentGetFailureReason.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'error_code'" do
    it "should work" do
      # instance = Plaid::TransferIntentGetFailureReason.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'error_message'" do
    it "should work" do
      # instance = Plaid::TransferIntentGetFailureReason.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
