#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::TransferTestClock
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/transfer_test_clock"

describe Plaid::TransferTestClock do
  describe "test an instance of TransferTestClock" do
    it "should create an instance of TransferTestClock" do
      # instance = Plaid::TransferTestClock.new
      # (instance).should be_a(Plaid::TransferTestClock)
    end
  end

  describe "test attribute 'test_clock_id'" do
    it "should work" do
      # instance = Plaid::TransferTestClock.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'virtual_time'" do
    it "should work" do
      # instance = Plaid::TransferTestClock.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
