#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::ValidationSources
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/validation_sources"

describe Plaid::ValidationSources do
  describe "test an instance of ValidationSources" do
    it "should create an instance of ValidationSources" do
      # instance = Plaid::ValidationSources.new
      # (instance).should be_a(Plaid::ValidationSources)
    end
  end

  describe "test attribute 'validation_source'" do
    it "should work" do
      # instance = Plaid::ValidationSources.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
