#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::WalletTransactionListRequestOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/wallet_transaction_list_request_options"

describe Plaid::WalletTransactionListRequestOptions do
  describe "test an instance of WalletTransactionListRequestOptions" do
    it "should create an instance of WalletTransactionListRequestOptions" do
      # instance = Plaid::WalletTransactionListRequestOptions.new
      # (instance).should be_a(Plaid::WalletTransactionListRequestOptions)
    end
  end

  describe "test attribute 'start_time'" do
    it "should work" do
      # instance = Plaid::WalletTransactionListRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'end_time'" do
    it "should work" do
      # instance = Plaid::WalletTransactionListRequestOptions.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
