#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::WalletTransactionExecuteResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/wallet_transaction_execute_response"

describe Plaid::WalletTransactionExecuteResponse do
  describe "test an instance of WalletTransactionExecuteResponse" do
    it "should create an instance of WalletTransactionExecuteResponse" do
      # instance = Plaid::WalletTransactionExecuteResponse.new
      # (instance).should be_a(Plaid::WalletTransactionExecuteResponse)
    end
  end

  describe "test attribute 'transaction_id'" do
    it "should work" do
      # instance = Plaid::WalletTransactionExecuteResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'status'" do
    it "should work" do
      # instance = Plaid::WalletTransactionExecuteResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::WalletTransactionExecuteResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
