#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for Plaid::WatchlistScreeningIndividualHistoryListResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/plaid/models/watchlist_screening_individual_history_list_response"

describe Plaid::WatchlistScreeningIndividualHistoryListResponse do
  describe "test an instance of WatchlistScreeningIndividualHistoryListResponse" do
    it "should create an instance of WatchlistScreeningIndividualHistoryListResponse" do
      # instance = Plaid::WatchlistScreeningIndividualHistoryListResponse.new
      # (instance).should be_a(Plaid::WatchlistScreeningIndividualHistoryListResponse)
    end
  end

  describe "test attribute 'watchlist_screenings'" do
    it "should work" do
      # instance = Plaid::WatchlistScreeningIndividualHistoryListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'next_cursor'" do
    it "should work" do
      # instance = Plaid::WatchlistScreeningIndividualHistoryListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'request_id'" do
    it "should work" do
      # instance = Plaid::WatchlistScreeningIndividualHistoryListResponse.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
