#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

require "../../core"

module Plaid
  class AccountSubtype
    include OpenApi::Validatable
    include OpenApi::Json

    property data : String

    ERROR_MESSAGE = %{invalid value for "AccountSubtype", must be one of ["401a", "401k", "403B", "457b", "529", "brokerage", "cash isa", "crypto exchange", "education savings account", "ebt", "fixed annuity", "gic", "health reimbursement arrangement", "hsa", "isa", "ira", "lif", "life insurance", "lira", "lrif", "lrsp", "non-custodial wallet", "non-taxable brokerage account", "other", "other insurance", "other annuity", "prif", "rdsp", "resp", "rlif", "rrif", "pension", "profit sharing plan", "retirement", "roth", "roth 401k", "rrsp", "sep ira", "simple ira", "sipp", "stock plan", "thrift savings plan", "tfsa", "trust", "ugma", "utma", "variable annuity", "credit card", "paypal", "cd", "checking", "savings", "money market", "prepaid", "auto", "business", "commercial", "construction", "consumer", "home equity", "loan", "mortgage", "overdraft", "line of credit", "student", "cash management", "keogh", "mutual fund", "recurring", "rewards", "safe deposit", "sarsep", "payroll", "null"].}

    VALID_VALUES = String.static_array("401a", "401k", "403B", "457b", "529", "brokerage", "cash isa", "crypto exchange", "education savings account", "ebt", "fixed annuity", "gic", "health reimbursement arrangement", "hsa", "isa", "ira", "lif", "life insurance", "lira", "lrif", "lrsp", "non-custodial wallet", "non-taxable brokerage account", "other", "other insurance", "other annuity", "prif", "rdsp", "resp", "rlif", "rrif", "pension", "profit sharing plan", "retirement", "roth", "roth 401k", "rrsp", "sep ira", "simple ira", "sipp", "stock plan", "thrift savings plan", "tfsa", "trust", "ugma", "utma", "variable annuity", "credit card", "paypal", "cd", "checking", "savings", "money market", "prepaid", "auto", "business", "commercial", "construction", "consumer", "home equity", "loan", "mortgage", "overdraft", "line of credit", "student", "cash management", "keogh", "mutual fund", "recurring", "rewards", "safe deposit", "sarsep", "payroll", "null")

    delegate to_json_object_key, to: @data

    def self.from_json(value : JSON::PullParser) : AccountSubtype
      new(value)
    end

    def self.to_json(value : AccountSubtype, json : JSON::Builder) : Nil
      value.to_json(json)
    end

    def self.new(pull : JSON::PullParser)
      new(String.new(pull), false)
    end

    def self.from_json_object_key?(key : String)
      String.from_json_object_key?(key)
    end

    def initialize(@data : String, strict : Bool = true)
      validate if strict
    end

    def error_message : String
      ERROR_MESSAGE
    end

    def list_invalid_properties : Array(String)
      errors = Array(String).new
      errors.push(error_message) unless valid?
      errors
    end

    def valid? : Bool
      OpenApi::EnumValidator.valid?(data, VALID_VALUES, false)
    end

    def validate : Nil
      OpenApi::EnumValidator.validate("AccountSubtype", data, VALID_VALUES, false)
    end

    def to_json(json : JSON::Builder) : Nil
      @data.to_json(json)
    end

    def_equals_and_hash(@data)
  end
end
