#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./identity_verification_request_user"
require "./identity_verification_retry_request_steps_object"
require "./strategy"

module Plaid
  # Request input for retrying an identity verification attempt
  class IdentityVerificationRetryRequest
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Required Properties

    # A unique ID that identifies the end user in your system. This ID can also be used to associate user-specific data from other Plaid products. Financial Account Matching requires this field and the `/link/token/create` `client_user_id` to be consistent. Personally identifiable information, such as an email address or phone number, should not be used in the `client_user_id`.
    @[JSON::Field(key: "client_user_id", type: String?, default: nil, required: true, nullable: false, emit_null: false)]
    getter client_user_id : String? = nil
    MIN_LENGTH_FOR_CLIENT_USER_ID = 1

    # ID of the associated Identity Verification template.
    @[JSON::Field(key: "template_id", type: String?, default: nil, required: true, nullable: false, emit_null: false)]
    getter template_id : String? = nil

    @[JSON::Field(key: "strategy", type: Plaid::Strategy?, default: nil, required: true, nullable: false, emit_null: false)]
    getter strategy : Plaid::Strategy? = nil

    # End of Required Properties

    # Optional Properties

    @[JSON::Field(key: "user", type: IdentityVerificationRequestUser?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: user.nil? && !user_present?)]
    getter user : IdentityVerificationRequestUser? = nil

    @[JSON::Field(ignore: true)]
    property? user_present : Bool = false

    @[JSON::Field(key: "steps", type: Plaid::IdentityVerificationRetryRequestStepsObject?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: steps.nil? && !steps_present?)]
    getter steps : Plaid::IdentityVerificationRetryRequestStepsObject? = nil

    @[JSON::Field(ignore: true)]
    property? steps_present : Bool = false

    # Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    @[JSON::Field(key: "client_id", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter client_id : String? = nil

    # Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    @[JSON::Field(key: "secret", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter secret : String? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Required properties
      @client_user_id : String? = nil,
      @template_id : String? = nil,
      @strategy : Plaid::Strategy? = nil,
      # Optional properties
      @user : IdentityVerificationRequestUser? = nil,
      @steps : Plaid::IdentityVerificationRetryRequestStepsObject? = nil,
      @client_id : String? = nil,
      @secret : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      invalid_properties.push("\"client_user_id\" is required and cannot be null") if @client_user_id.nil?

      unless (_client_user_id = @client_user_id).nil?
        if min_length_error = OpenApi::PrimitiveValidator.min_length_error("client_user_id", _client_user_id.to_s.size, MIN_LENGTH_FOR_CLIENT_USER_ID)
          invalid_properties.push(min_length_error)
        end
      end
      invalid_properties.push("\"template_id\" is required and cannot be null") if @template_id.nil?

      unless (_template_id = @template_id).nil?
      end
      invalid_properties.push("\"strategy\" is required and cannot be null") if @strategy.nil?

      unless (_strategy = @strategy).nil?
        invalid_properties.push(_strategy.error_message) if !_strategy.valid?
      end
      unless (_user = @user).nil?
      end
      unless (_steps = @steps).nil?
        invalid_properties.concat(_steps.list_invalid_properties_for("steps")) if _steps.is_a?(OpenApi::Validatable)
      end
      unless (_client_id = @client_id).nil?
      end
      unless (_secret = @secret).nil?
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      return false if @client_user_id.nil?
      unless (_client_user_id = @client_user_id).nil?
        return false if _client_user_id.to_s.size < MIN_LENGTH_FOR_CLIENT_USER_ID
      end

      return false if @template_id.nil?
      unless (_template_id = @template_id).nil?
      end

      return false if @strategy.nil?
      unless (_strategy = @strategy).nil?
        return false if !_strategy.valid?
      end

      unless (_user = @user).nil?
      end

      unless (_steps = @steps).nil?
        return false if _steps.is_a?(OpenApi::Validatable) && !_steps.valid?
      end

      unless (_client_id = @client_id).nil?
      end

      unless (_secret = @secret).nil?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] client_user_id Object to be assigned
    def client_user_id=(new_value : String?)
      raise ArgumentError.new("\"client_user_id\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_min_length("client_user_id", new_value.to_s.size, MIN_LENGTH_FOR_CLIENT_USER_ID)
      end

      @client_user_id = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] template_id Object to be assigned
    def template_id=(new_value : String?)
      raise ArgumentError.new("\"template_id\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
      end

      @template_id = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] strategy Object to be assigned
    def strategy=(new_value : Plaid::Strategy?)
      raise ArgumentError.new("\"strategy\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
        new_value.validate
      end

      @strategy = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] user Object to be assigned
    def user=(new_value : IdentityVerificationRequestUser?)
      unless new_value.nil?
      end

      @user = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] steps Object to be assigned
    def steps=(new_value : Plaid::IdentityVerificationRetryRequestStepsObject?)
      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @steps = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] client_id Object to be assigned
    def client_id=(new_value : String?)
      unless new_value.nil?
      end

      @client_id = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] secret Object to be assigned
    def secret=(new_value : String?)
      unless new_value.nil?
      end

      @secret = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@client_user_id, @template_id, @strategy, @user, @user_present, @steps, @steps_present, @client_id, @secret)
  end
end
