#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./income_verification_precheck_confidence"

module Plaid
  # IncomeVerificationPrecheckResponse defines the response schema for `/income/verification/precheck`.
  class IncomeVerificationPrecheckResponse
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Required Properties

    # ID of the precheck. Provide this value when calling `/link/token/create` in order to optimize Link conversion.
    @[JSON::Field(key: "precheck_id", type: String?, default: nil, required: true, nullable: false, emit_null: false)]
    getter precheck_id : String? = nil

    # A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    @[JSON::Field(key: "request_id", type: String?, default: nil, required: true, nullable: false, emit_null: false)]
    getter request_id : String? = nil

    @[JSON::Field(key: "confidence", type: Plaid::IncomeVerificationPrecheckConfidence?, default: nil, required: true, nullable: false, emit_null: false)]
    getter confidence : Plaid::IncomeVerificationPrecheckConfidence? = nil

    # End of Required Properties

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Required properties
      @precheck_id : String? = nil,
      @request_id : String? = nil,
      @confidence : Plaid::IncomeVerificationPrecheckConfidence? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      invalid_properties.push("\"precheck_id\" is required and cannot be null") if @precheck_id.nil?

      unless (_precheck_id = @precheck_id).nil?
      end
      invalid_properties.push("\"request_id\" is required and cannot be null") if @request_id.nil?

      unless (_request_id = @request_id).nil?
      end
      invalid_properties.push("\"confidence\" is required and cannot be null") if @confidence.nil?

      unless (_confidence = @confidence).nil?
        invalid_properties.push(_confidence.error_message) if !_confidence.valid?
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      return false if @precheck_id.nil?
      unless (_precheck_id = @precheck_id).nil?
      end

      return false if @request_id.nil?
      unless (_request_id = @request_id).nil?
      end

      return false if @confidence.nil?
      unless (_confidence = @confidence).nil?
        return false if !_confidence.valid?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] precheck_id Object to be assigned
    def precheck_id=(new_value : String?)
      raise ArgumentError.new("\"precheck_id\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
      end

      @precheck_id = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] request_id Object to be assigned
    def request_id=(new_value : String?)
      raise ArgumentError.new("\"request_id\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
      end

      @request_id = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] confidence Object to be assigned
    def confidence=(new_value : Plaid::IncomeVerificationPrecheckConfidence?)
      raise ArgumentError.new("\"confidence\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
        new_value.validate
      end

      @confidence = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@precheck_id, @request_id, @confidence)
  end
end
