#  The Plaid API
#
# The Plaid REST API. Please see https://plaid.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-09-14_1.474.3
#
# Generated by: https://openapi-generator.tech
#
# OpenAPI Generator version: 7.1.0-SNAPSHOT

# Dependencies
require "crest"
require "log"
require "json"
require "time"
require "uri"

# Project files
require "./ext/**"
require "./validators/**"
require "./plaid/configuration.cr"
require "./plaid/api_error.cr"
require "./plaid/api_client.cr"

module Plaid
  Log = ::Log.for("Plaid") # => Log for Plaid source

  VERSION = {{ `shards version #{__DIR__}`.chomp.stringify }}

  # Return the default `Configuration` object.
  def self.configure
    Configuration.default
  end

  # Customize default settings for the SDK using block.
  #
  # ```
  # Plaid.configure do |config|
  #   config.username = "xxx"
  #   config.password = "xxx"
  # end
  # ```
  def self.configure(&)
    yield Configuration.default
  end
end
